<?php
/**
 * TCP Document Library - Configuration Example
 *
 * This file shows example configuration values.
 * These are set in WordPress admin settings, not in this file.
 * This is for reference only.
 */

// DO NOT EDIT THIS FILE
// All configuration is done through WordPress admin at:
// TCP Documents > Settings

/*
 * Google Sheets Configuration
 */

// Google Sheets API Key
// Get from: https://console.cloud.google.com/apis/credentials
// Example: 'AIzaSyB...'
define('TCP_DOCS_GOOGLE_API_KEY_EXAMPLE', 'your-api-key-here');

// Google Spreadsheet ID
// Found in spreadsheet URL: https://docs.google.com/spreadsheets/d/[ID]/edit
// Default: 1rt5pbD51f8oqDIDC0FYQcFQmE5ziehCNiFs4mWBRzRw
define('TCP_DOCS_SPREADSHEET_ID_EXAMPLE', '1rt5pbD51f8oqDIDC0FYQcFQmE5ziehCNiFs4mWBRzRw');

// Sheet/Tab Name
// Default: 'File Data'
define('TCP_DOCS_SHEET_NAME_EXAMPLE', 'File Data');

/*
 * General Settings
 */

// Auto-sync on user login
// Default: true
define('TCP_DOCS_AUTO_SYNC_EXAMPLE', true);

// Require login to view documents
// Default: true
define('TCP_DOCS_REQUIRE_LOGIN_EXAMPLE', true);

/*
 * Google Sheet Column Mapping
 *
 * Your Google Sheet should have these columns:
 * - Title (required)
 * - Description
 * - Category (Urethanes, Epoxies, Sealers etc) - flexible matching
 * - Brand
 * - Document Type (SDS, TDS, Marketing) - flexible matching
 * - HubSpot File URL (required - unique identifier)
 * - HubSpot File ID
 * - Google Drive File URL (optional - not used)
 * - File Name
 * - Last Updated (optional - not used)
 *
 * Note: Column headers with parentheses are supported. The plugin
 * will match "Category" or "Category (Urethanes, Epoxies, Sealers etc)"
 */

/*
 * Available Categories
 */
$tcp_categories_example = array(
    'Epoxies',
    'Polyaspartics',
    'Urethanes',
    'Sealers',
    'Dyes/Stains',
    'Cementitious'
);

/*
 * Available Brands
 */
$tcp_brands_example = array(
    'The Concrete Protector',
    'Match Patch Pro',
    'Scientific Concrete Polishing',
    'Sani-Tred'
);

/*
 * Document Types
 */
$tcp_document_types_example = array(
    'TDS', // Technical Data Sheet
    'SDS'  // Safety Data Sheet
);

/*
 * API Endpoints
 *
 * The plugin registers these REST endpoints:
 *
 * Public (require login):
 * - GET  /wp-json/tcp-docs/v1/documents
 * - GET  /wp-json/tcp-docs/v1/documents/{id}
 * - GET  /wp-json/tcp-docs/v1/filters
 * - GET  /wp-json/tcp-docs/v1/auth/user
 *
 * Admin (require manage_options capability):
 * - POST /wp-json/tcp-docs/v1/admin/sync
 * - POST /wp-json/tcp-docs/v1/admin/test-connection
 */

/*
 * Shortcode Usage Examples
 */

// Basic usage
// [tcp_documents]

// With category filter
// [tcp_documents category="Epoxies"]

// With brand filter
// [tcp_documents brand="The Concrete Protector"]

// With type filter
// [tcp_documents document_type="TDS"]

// Combined filters
// [tcp_documents category="Polyaspartics" brand="The Concrete Protector"]

// With search
// [tcp_documents search="concrete sealer"]
